Repository teamGrowing/growing-web, pull requests merged in 2023-04, with the labels that each got.

#34 Feat/calendar
  package.json
  src/Routes.tsx
  src/components/common/Modal/ModalBottomSheet/ModalBottomSheet.tsx
  src/components/pages/calendar/CalendarBottomSheet.tsx
  src/components/pages/calendar/CalendarTitle.stories.tsx
  src/components/pages/calendar/CalendarTitle.tsx
  src/components/pages/calendar/TodoArea.tsx
  src/constants/ments.ts
  src/constants/queryKeys.ts
  src/hooks/queries/calendar.queries.ts
  src/pages/calendar/CalendarPage.tsx
  src/services/plan.service.ts
  src/types/plan/PatchPlan.dto.ts
  src/util/Calendar.ts
  yarn.lock
Labels: 🌈 enhancement, 💫 New, ✅ Fix

#35 Fix/more
  src/components/common/ToastMessage/ToastMessage.tsx
  src/components/pages/more/PetCard.tsx
  src/components/pages/more/PetDetailCard.tsx
  src/pages/more/InfoPage.tsx
  src/pages/more/MoreMainPage.tsx
  src/styles/common/keyframs.ts
Labels: 🌈 enhancement, ✅ Fix

#38 Feature/36
  src/assets/icons/IconMute.svg
  src/assets/icons/IconPause.svg
  src/assets/icons/IconPlay.svg
  src/assets/icons/IconUnmute.svg
  src/assets/icons/index.ts
  src/components/pages/chat/ArchivedCard.tsx
  src/components/pages/chat/ChatBallon.tsx
  src/components/pages/chat/ChatVideo.tsx
  src/components/pages/chat/InputChat.tsx
  src/components/pages/chat/SubMenu.tsx
  src/components/pages/chat/VideoPlayBtn.tsx
  src/components/pages/chat/plus-menu/PlusMenu.tsx
  src/components/pages/chat/plus-menu/PlusMenuGallery.tsx
  src/hooks/common/useVideo.ts
  src/pages/chat/ChatPhotoBoxPage.tsx
  src/pages/chat/ChatPhotoDetailPage.tsx
  src/types/chat/ChatPhoto.dto.ts
  src/util/Text.ts
Labels: 💫 New

#40 fix: prevent video full screen in webview (#39)
  src/components/pages/chat/ChatVideo.tsx
Labels: 🐛 bug

#41 feat: 카카오 로그인 기능 추가 (#37)
  package.json
  public/index.html
  src/Routes.tsx
  src/assets/icons/IconTalk.svg
  src/assets/icons/index.ts
  src/assets/image/Egg.png
  src/assets/image/Logo.png
  src/assets/image/PetsWaiting.png
  src/assets/image/index.ts
  src/components/pages/home/HomePet.tsx
  src/components/pages/home/Pet3D.tsx
  src/components/pages/login/Egg.tsx
  src/components/pages/login/LoginButton.tsx
  src/components/pages/login/Wave.tsx
  src/constants/ments.ts
  src/constants/queryKeys.ts
  src/hooks/queries/couple.queries.ts
  src/hooks/queries/user.queries.ts
  src/hooks/user/useSignUp.ts
  src/pages/Login.tsx
  src/pages/chat/ChattingPage.tsx
  src/pages/home/Home.tsx
  src/pages/login/LoginCreatePage.tsx
  src/pages/login/LoginInvitedPage.tsx
  src/pages/login/LoginKakaoPage.tsx
  src/pages/login/LoginPetBornPage.tsx
  src/pages/login/LoginSelectPage.tsx
  src/pages/login/LoginWaitingPage.tsx
  src/services/auth.service.ts
  src/services/user.service.ts
  src/stores/UserStore.ts
  src/styles/GlobalStyle.tsx
  src/types/InputSchema.ts
  src/types/auth/LogInResult.dto.ts
  src/types/auth/RefreshResponse.dto.ts
  src/types/auth/VerifyCode.dto.ts
  src/types/auth/VerifyCodeResponse.dto.ts
  src/util/AuthRoute.tsx
  yarn.lock
Labels: 💫 New
