Repository teamGrowing/growing-web, pull requests merged in 2023-03, with the labels that each got.

#28 Feat/gallery
  src/components/layout/BottomNavigation.tsx
  src/components/layout/NavItem.tsx
  src/hooks/queries/album.queries.ts
  src/hooks/queries/gallery.queries.ts
  src/pages/gallery/AlbumDetailPage.tsx
  src/pages/gallery/AlbumPage.tsx
  src/pages/gallery/AlbumPhotoDetailPage.tsx
  src/pages/gallery/GalleryMainPage.tsx
  src/pages/gallery/NewAlbumPage.tsx
  src/pages/gallery/PhotoDetailPage.tsx
  src/pages/gallery/PhotoPage.tsx
  src/types/gallery/CreatePhotoResponse.dto.ts
Labels: 🌈 enhancement, 💫 New, ✅ Fix

#29 Feat/more
  src/assets/image/DefaultProfile.png
  src/components/common/Modal/ModalBottomSheet/BottomSheetMenu.tsx
  src/components/layout/BottomNavigation.tsx
  src/components/pages/gallery/AlbumRowContainer.tsx
  src/components/pages/gallery/BottomMenu.tsx
  src/components/pages/gallery/FloatingButton.tsx
  src/components/pages/gallery/Photo.tsx
  src/components/pages/gallery/PhotoContainer.tsx
  src/components/pages/gallery/PhotoDetail.tsx
  src/components/pages/gallery/PhotoScroll.tsx
  src/components/pages/more/InputContainer.tsx
  src/components/pages/more/PetCard.tsx
  src/components/pages/more/PetDetailCard.stories.tsx
  src/components/pages/more/PetDetailCard.tsx
  src/components/pages/more/WhiteContainer.tsx
  src/hooks/queries/album.queries.ts
  src/hooks/queries/couple.queries.ts
  src/hooks/queries/gallery.queries.ts
  src/hooks/queries/pet.queries.ts
  src/hooks/queries/user.queries.ts
  src/pages/gallery/AlbumDetailPage.tsx
  src/pages/gallery/AlbumPage.tsx
  src/pages/gallery/AlbumPhotoDetailPage.tsx
  src/pages/gallery/GalleryMainPage.tsx
  src/pages/gallery/PhotoDetailPage.tsx
  src/pages/gallery/PhotoPage.tsx
  src/pages/gallery/context.ts
  src/pages/home/Home.tsx
  src/pages/more/InfoPage.tsx
  src/pages/more/MoreMainPage.tsx
  src/pages/more/PetPage.tsx
  src/pages/more/ProfilePage.tsx
  src/pages/more/SettingPage.tsx
  src/services/pet.service.ts
  src/services/user.service.ts
  src/stores/UserStore.ts
  src/styles/GlobalStyle.tsx
  src/types/chat/CreatePhoto.dto.ts
  src/types/gallery/Photo.dto.ts
  src/types/gallery/PhotoLine.dto.ts
  src/types/user/ChangeUserPhoto.dto.ts
Labels: 🌈 enhancement

#32 Feat/home
  package.json
  src/Routes.tsx
  src/assets/lottie/congratsAnimation.json
  src/components/pages/home/HomePet.tsx
  src/components/pages/home/Pet3D.tsx
  src/components/pages/home/PetGauge.tsx
  src/constants/ments.ts
  src/hooks/queries/pet.queries.ts
  src/pages/home/PetGraudatePage.tsx
  src/pages/home/PetNamingPage.tsx
  src/pages/home/PetRaisingPage.tsx
  src/services/pet.service.ts
  src/types/pet/Pet.dto.ts
  src/types/pet/PetReaction.dto.ts
  yarn.lock
Labels: 🌈 enhancement, ✅ Fix

#33 Feat/webview
  .eslintrc.json
  public/apple-touch-icon.png
  public/favicon.ico
  public/growing.svg
  public/index.html
  public/logo512.png
  public/manifest.json
  src/App.tsx
  src/components/common/FullScreenError.tsx
  src/components/common/FullScreenLoader.tsx
  src/components/common/Modal/AlbumModal.tsx
  src/components/common/Modal/ModalBottomSheet/ModalBottomSheet.tsx
  src/components/common/TopBar/TopBar.tsx
  src/components/layout/BottomNavigation.tsx
  src/components/pages/chat/ChatNotice.tsx
  src/components/pages/chat/InputChat.tsx
  src/components/pages/chat/SubMenu.tsx
  src/components/pages/chat/plus-menu/Emojis.tsx
  src/components/pages/chat/plus-menu/PlusMenuEmoji.tsx
  src/components/pages/chat/plus-menu/PlusMenuGallery.tsx
  src/components/pages/gallery/FloatingButton.tsx
  src/components/pages/gallery/GalleryTitle.tsx
  src/components/pages/gallery/PhotoScroll.tsx
  src/components/pages/home/Pet3D.tsx
  src/components/pages/home/PetGauge.tsx
  src/components/pages/home/PetModel.tsx
  src/components/pages/more/PetCard.tsx
  src/constants/queryKeys.ts
  src/hooks/queries/pet.queries.ts
  src/index.tsx
  src/pages/Login.tsx
  src/pages/chat/ChattingPage.tsx
  src/pages/gallery/AlbumDetailPage.tsx
  src/pages/gallery/PhotoPage.tsx
  src/pages/home/PetRaisingPage.tsx
  src/pages/more/MoreMainPage.tsx
  src/pages/more/PetPage.tsx
  src/services/pet.service.ts
  src/styles/GlobalStyle.tsx
  webpack.config.js
Labels: ✅ Fix
