Repository teamGrowing/growing-web, pull requests merged in 2023-05, with the labels that each got.

#47 design: add normalize.css (#43)
  package.json
  src/styles/GlobalStyle.tsx
  yarn.lock
Labels: 🌈 enhancement

#46 feat: 채팅 복사, 삭제 기능 추가 (#42)
  src/components/pages/chat/ChatBallon.tsx
  src/components/pages/chat/ChatContextMenu.tsx
  src/components/pages/chat/InputChat.tsx
  src/components/pages/chat/plus-menu/PlusMenu.tsx
  src/components/pages/chat/plus-menu/PlusMenuGallery.tsx
  src/constants/ments.ts
  src/pages/chat/ChattingPage.tsx
Labels: 💫 New

#50 Feat/gallery
  package.json
  src/Routes.tsx
  src/components/pages/chat/ChatVideo.tsx
  src/components/pages/gallery/GalleryTitle.tsx
  src/components/pages/gallery/PhotoContainer.tsx
  src/components/pages/gallery/PhotoDetail.tsx
  src/components/pages/gallery/PhotoScroll.tsx
  src/constants/constants.ts
  src/constants/ments.ts
  src/hooks/queries/gallery.queries.ts
  src/pages/chat/ChatPhotoDetailPage.tsx
  src/pages/gallery/AlbumDetailPage.tsx
  src/pages/gallery/AlbumPage.tsx
  src/pages/gallery/AlbumPhotoDetailPage.tsx
  src/pages/gallery/GalleryMainPage.tsx
  src/pages/gallery/NewAlbumPage.tsx
  src/pages/gallery/PhotoDetailPage.tsx
  src/pages/gallery/PhotoPage.tsx
  src/services/gallery.service.ts
  yarn.lock
Labels: 🌈 enhancement, ✅ Fix

#55 fix: move to login page when refresh logic failed (#54)
  src/util/AuthRoute.tsx
Labels: 🐛 bug

#57 fix: fix scroll issue on chatting page (#51)
  src/components/pages/chat/ChatBallon.tsx
  src/components/pages/chat/ChatContextMenu.tsx
  src/components/pages/chat/InputChat.tsx
  src/components/pages/chat/plus-menu/PlusMenu.tsx
  src/constants/constants.ts
  src/hooks/chat/useReactQuerySubscription.ts
  src/hooks/common/useLongPress.ts
  src/pages/chat/ChattingPage.tsx
  src/pages/chat/LongChattingPage.tsx
  src/stores/ChatStore.ts
  src/styles/GlobalStyle.tsx
Labels: 🐛 bug

#58 fix: fix pet gauge max issue (#53)
  src/pages/home/PetRaisingPage.tsx
Labels: 🐛 bug
