Repository teamGrowing/growing-web, pull requests merged in 2024-02, with the labels that each got.

#69 ci: husky 설정 추가
  .cz-config.js
  .eslintignore
  .eslintrc.json
  .github/CODEOWNERS
  .github/pull_request_template.md
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .nvmrc
  commitlint.config.ts
  package.json
  yarn.lock
Labels: 👷🏻‍♂️ ci

#76 feat: socket mocking 도입
  package.json
  src/libs/socket.io-client/index.ts
  src/mocks/chat/chatArcivedHandler.ts
  src/mocks/chat/chatHandler.ts
  src/mocks/chat/chatNoticeHandler.ts
  src/mocks/chat/index.ts
  src/mocks/socket/index.ts
  src/mocks/socket/socket.io-mock.d.ts
  src/mocks/user/getEmojiDetailHandler.ts
  src/pages/chat/components/ChatNotice/ChatNotice.styled.ts
  src/pages/chat/hooks/useReactQuerySubscription.ts
  yarn.lock
Labels: ✨ feat

#79 design: 디자인 개편
  src/assets/image/Heart.png
  src/assets/image/index.ts
  src/components/common/TopBar/TopBar.styled.ts
  src/components/common/TopBar/types/TopBarMode.ts
  src/mocks/chat/data/chatData.ts
  src/mocks/chat/data/heart.png
  src/pages/gallery/components/Album/Album.styled.ts
  src/pages/home/HomePage/HomePage.styled.ts
  src/pages/home/PetGraduatePage/PetGraduatePage.styled.ts
  src/pages/home/PetGraduatePage/PetGraduatePage.tsx
  src/pages/home/PetRaisingPage/PetRaisingPage.styled.ts
  src/pages/home/PetRaisingPage/PetRaisingPage.tsx
  src/pages/home/components/HomePet/HomePet.styled.ts
  src/pages/home/components/HomePet/HomePet.tsx
  src/pages/home/components/PetGauge/PetGauge.styled.ts
  src/pages/home/components/PetModel.tsx
  src/pages/home/components/PetRaisingMenu/PetRaisingMenu.styled.ts
  src/pages/home/components/PetRaisingMenu/PetRaisingMenu.tsx
  src/pages/more/InfoPage/InfoPage.tsx
  src/pages/more/MoreMainPage/MoreMainPage.styled.ts
  src/pages/more/NoticeDetailPage/NoticeDetailPage.tsx
  src/pages/more/NoticePage/NoticePage.tsx
  src/pages/more/PetPage/PetPage.styled.ts
  src/pages/more/PetPage/PetPage.tsx
  src/pages/more/SettingPage/SettingPage.tsx
  src/pages/more/components/InputContainer/InputContainer.styled.ts
  src/pages/more/components/MenuBox/MenuBox.styled.ts
  src/pages/more/components/MenuBox/MenuBox.tsx
  src/pages/more/components/PetCard/PetCard.styled.ts
  src/pages/more/components/PetDetailCard/PetDetailCard.styled.ts
  src/pages/more/components/Profile/Profile.styled.ts
  src/pages/more/components/SideButton/SideButton.styled.ts
  src/pages/more/components/WhiteContainer/WhiteContainer.styled.ts
  src/styles/GlobalStyle.tsx
  src/styles/common/MainBackground.ts
  src/styles/common/animation.ts
  src/styles/theme/DefaultTheme.ts
  src/types/styled.d.ts
Labels: 🎨 design

#80 refactor: mocking
  src/hooks/queries/album.ts
  src/hooks/queries/gallery.ts
  src/mocks/album/data/index.ts
  src/mocks/album/deleteAlbumHandler.ts
  src/mocks/album/getAlbumsHandler.ts
  src/mocks/album/postAlbumsHandler.ts
  src/mocks/gallery/createPhotoHandler.ts
  src/mocks/gallery/data/data.ts
  src/mocks/gallery/deleteCommentHandler.ts
  src/mocks/gallery/deletePhotoHandler.ts
  src/mocks/gallery/getCommentsHandler.ts
  src/mocks/gallery/getPhotosHandler.ts
  src/mocks/gallery/postCommentHandler.ts
  src/mocks/plan/data/plans.ts
  src/mocks/plan/deletePlanHandler.ts
  src/mocks/plan/getPlansHandler.ts
  src/mocks/plan/patchPlanHandler.ts
  src/mocks/plan/postPlanHandler.ts
Labels: ♻️ refactor
